from datetime import datetime

backtest_configs = [
        # {
        #     "put_pct": 1, 
        #     "spread_search": "1:4",
        #     "aa": 1,
        #     "risk_unit": .025,
        #     "model": "CDVOLVARVC_AA1",
        #     "vc_level":"75+150+300+300",
        #     "capital_distributions": ".33,.33,.33",
        #     "portfolio_cash": 20000,
        #     "volatility_threshold": 0.5,
        #     "user": "cm3",
        #     "threeD_vol": "return_vol_10D",
        #     "dataset": "CDVOLBF3-55PE2",
        #     "spread_length": 3,
        #     "reserve_cash": 3,
        #     "spread_type": "standard",
        #     "scale": "DS",
        #     "divisor": 3,
        #     "reup": "hot",
        #     "IDX": False
        # },
        # {
        #     "put_pct": 1, 
        #     "spread_search": "1:4",
        #     "aa": 1,
        #     "risk_unit": .025,
        #     "model": "CDVOLVARVC_AA1",
        #     "vc_level":"75+150+300+300",
        #     "capital_distributions": ".33,.33,.33",
        #     "portfolio_cash": 20000,
        #     "volatility_threshold": 0.5,
        #     "user": "cm3",
        #     "threeD_vol": "return_vol_10D",
        #     "dataset": "CDVOLBF3-55PE2",
        #     "spread_length": 3,
        #     "reserve_cash": 5000,
        #     "spread_type": "standard",
        #     "scale": "DS",
        #     "divisor": 3,
        #     "reup": "hot",
        #     "IDX": False
        # },
        # {
        #     "put_pct": 1, 
        #     "spread_search": "1:4",
        #     "aa": 0,
        #     "risk_unit": .0475,
        #     "model": "CDVOLVARVC",
        #     "vc_level":"100+200+400+300",
        #     "capital_distributions": ".33,.33,.33",
        #     "portfolio_cash": 20000,
        #     "volatility_threshold": 0.5,
        #     "user": "cm3",
        #     "threeD_vol": "return_vol_10D",
        #     "dataset": "CDVOLBF3-6PE2",
        #     "spread_length": 3,
        #     "reserve_cash": 3,
        #     "spread_type": "standard",
        #     "scale": "DS",
        #     "divisor": .75,
        #     "reup": "hot",
        #     "IDX": False
        #     },
        # {
        #     "put_pct": 1, 
        #     "spread_search": "1:4",
        #     "aa": 0,
        #     "risk_unit": .0475,
        #     "model": "CDVOLVARVC",
        #     "vc_level":"100+200+400+300",
        #     "capital_distributions": ".33,.33,.33",
        #     "portfolio_cash": 20000,
        #     "volatility_threshold": 0.5,
        #     "user": "cm3",
        #     "threeD_vol": "return_vol_10D",
        #     "dataset": "CDVOLBF3-6PE2",
        #     "spread_length": 3,
        #     "reserve_cash": 5000,
        #     "spread_type": "standard",
        #     "scale": "DS",
        #     "divisor": .75,
        #     "reup": "hot",
        #     "IDX": False
        #     },
        #     {
        #     "put_pct": 1, 
        #     "spread_search": "1:4",
        #     "aa": 0,
        #     "risk_unit": .0475,
        #     "model": "CDVOLVARVC2",
        #     "vc_level":"100+200+400+300",
        #     "capital_distributions": ".33,.33,.33",
        #     "portfolio_cash": 20000,
        #     "volatility_threshold": 0.5,
        #     "user": "cm3",
        #     "threeD_vol": "return_vol_10D",
        #     "dataset": "CDVOLBF3-6PE2",
        #     "spread_length": 3,
        #     "reserve_cash": 3,
        #     "spread_type": "standard",
        #     "scale": "DS",
        #     "divisor": .75,
        #     "reup": "hot",
        #     "IDX": False
        #     },
        # {
        #     "put_pct": 1, 
        #     "spread_search": "1:4",
        #     "aa": 0,
        #     "risk_unit": .0475,
        #     "model": "CDVOLVARVC2",
        #     "vc_level":"100+200+400+300",
        #     "capital_distributions": ".33,.33,.33",
        #     "portfolio_cash": 20000,
        #     "volatility_threshold": 0.5,
        #     "user": "cm3",
        #     "threeD_vol": "return_vol_10D",
        #     "dataset": "CDVOLBF3-6PE2",
        #     "spread_length": 3,
        #     "reserve_cash": 5000,
        #     "spread_type": "standard",
        #     "scale": "DS",
        #     "divisor": .75,
        #     "reup": "hot",
        #     "IDX": False
        #     },
        #     {
        #     "put_pct": 1, 
        #     "spread_search": "1:4",
        #     "aa": 0,
        #     "risk_unit": .025,
        #     "model": "CDVOLVARVC2",
        #     "vc_level":"100+200+400+300",
        #     "capital_distributions": ".33,.33,.33",
        #     "portfolio_cash": 20000,
        #     "volatility_threshold": 0.5,
        #     "user": "cm3",
        #     "threeD_vol": "return_vol_10D",
        #     "dataset": "CDVOLBF3-55PE2",
        #     "spread_length": 3,
        #     "reserve_cash": 3,
        #     "spread_type": "standard",
        #     "scale": "DS",
        #     "divisor": .75,
        #     "reup": "hot",
        #     "IDX": False
        #     },
        # {
        #     "put_pct": 1, 
        #     "spread_search": "1:4",
        #     "aa": 0,
        #     "risk_unit": .025,
        #     "model": "CDVOLVARVC2",
        #     "vc_level":"100+200+400+300",
        #     "capital_distributions": ".33,.33,.33",
        #     "portfolio_cash": 20000,
        #     "volatility_threshold": 0.5,
        #     "user": "cm3",
        #     "threeD_vol": "return_vol_10D",
        #     "dataset": "CDVOLBF3-55PE2",
        #     "spread_length": 3,
        #     "reserve_cash": 5000,
        #     "spread_type": "standard",
        #     "scale": "DS",
        #     "divisor": .75,
        #     "reup": "hot",
        #     "IDX": False
        #     },
        #     {
        #     "put_pct": 1, 
        #     "spread_search": "1:4",
        #     "aa": 0,
        #     "risk_unit": .175,
        #     "model": "CDVOLVARVC2",
        #     "vc_level":"100+200+400+300",
        #     "capital_distributions": ".33,.33,.33",
        #     "portfolio_cash": 20000,
        #     "volatility_threshold": 0.5,
        #     "user": "cm3",
        #     "threeD_vol": "return_vol_10D",
        #     "dataset": "CDVOLBF3-6PE2",
        #     "spread_length": 3,
        #     "reserve_cash": 3,
        #     "spread_type": "standard",
        #     "scale": "DS",
        #     "divisor": .75,
        #     "reup": "hot",
        #     "IDX": True
        #     },
        # {
        #     "put_pct": 1, 
        #     "spread_search": "1:4",
        #     "aa": 0,
        #     "risk_unit": .125,
        #     "model": "CDVOLVARVC2",
        #     "vc_level":"100+200+400+300",
        #     "capital_distributions": ".33,.33,.33",
        #     "portfolio_cash": 20000,
        #     "volatility_threshold": 0.5,
        #     "user": "cm3",
        #     "threeD_vol": "return_vol_10D",
        #     "dataset": "CDVOLBF3-55PE2",
        #     "spread_length": 3,
        #     "reserve_cash": 5000,
        #     "spread_type": "standard",
        #     "scale": "DS",
        #     "divisor": .75,
        #     "reup": "hot",
        #     "IDX": True
        #     },
        {
            "put_pct": 1, 
            "spread_search": "1:4",
            "aa": 0,
            "risk_unit": 200,
            "model": "CDVOLVARVC",
            "vc_level":"100+250+400+300",
            "capital_distributions": ".33,.33,.33",
            "portfolio_cash": 40000,
            "volatility_threshold": 0.5,
            "user": "cm3",
            "threeD_vol": "return_vol_10D",
            "dataset": "CDVOLBF3-55PE2",
            "spread_length": 3,
            "reserve_cash": 5000,
            "spread_type": "standard",
            "scale": "DC",
            "divisor": .75,
            "reup": "hot",
            "IDX": False
        },
        {
            "put_pct": 1, 
            "spread_search": "1:4",
            "aa": 0,
            "risk_unit": 150,
            "model": "CDVOLVARVC",
            "vc_level":"100+250+400+300",
            "capital_distributions": ".33,.33,.33",
            "portfolio_cash": 40000,
            "volatility_threshold": 0.5,
            "user": "cm3",
            "threeD_vol": "return_vol_10D",
            "dataset": "CDVOLBF3-6PE2",
            "spread_length": 3,
            "reserve_cash": 5000,
            "spread_type": "standard",
            "scale": "DC",
            "divisor": .75,
            "reup": "hot",
            "IDX": False
        },
    ]


if __name__ == "__main__":
    years = [
    'twenty2',
    'twenty3',
    'twenty4',
    ]
    nowstr = datetime.now().strftime("%Y%m%d")
    year_data = {
        "twenty2": "22",
        "twenty3": "23",
        "twenty4": "24",
    }
    models_tested = []

    for config in backtest_configs:
        for year in years:
            trading_strat = f"{config['user']}/{nowstr}-{year_data[year]}:{config['reserve_cash']}:run2_{config['dataset']}_{config['model']}_{config['IDX']}_CD{config['capital_distributions']}_div{config['divisor']}_vol{config['volatility_threshold']}_{config['scale']}_vc{config['vc_level']}_sssl{config['spread_search']}:{config['spread_length']}"
            models_tested.append(f'{trading_strat}${config["portfolio_cash"]}_{config["risk_unit"]}')

    print(models_tested)
            