from datetime import datetime, timedelta
from io import StringIO
import os
import boto3
import pandas as pd
import requests
import json
import ast
import holidays

results = pd.read_csv('/Users/ogdiz/Projects/APE-Research/APE-Backtester/v1/BT_Results/IGNORE.csv')

full = [{
            "put_pct": 1, 
            "spread_adjustment": 0,
            "aa": 1,
            "risk_unit": .01,
            "model": "reg",
            "vc_level":"nvc",
            "portfolio_cash": 200000,
            "risk_adjustment": "0.1$0.3",
            "pos_limit": "poslimit",
            "standard_risk": "0.6",
            "volatility_threshold": 1
        },
        {
            "put_pct": 1, 
            "spread_adjustment": 0,
            "aa": 1,
            "risk_unit": .01,
            "model": "regVC",
            "vc_level":"200$",
            "portfolio_cash": 200000,
            "risk_adjustment": "0.1$0.3",
            "pos_limit": "poslimit",
            "standard_risk": "0.6",
            "volatility_threshold": 1
        },
        {
            "put_pct": 1, 
            "spread_adjustment": 0,
            "aa": 1,
            "risk_unit": .01,
            "model": "regVCSell",
            "vc_level":"200$",
            "portfolio_cash": 200000,
            "risk_adjustment": "0.1$0.3",
            "pos_limit": "poslimit",
            "standard_risk": "0.6",
            "volatility_threshold": 1
        },
        {
            "put_pct": 1, 
            "spread_adjustment": 0,
            "aa": 1,
            "risk_unit": .01,
            "model": "reg",
            "vc_level":"nvc",
            "portfolio_cash": 200000,
            "risk_adjustment": "0.1$0.3",
            "pos_limit": "poslimit",
            "standard_risk": "0.6",
            "volatility_threshold": 1.25
        },
        {
            "put_pct": 1, 
            "spread_adjustment": 0,
            "aa": 1,
            "risk_unit": .01,
            "model": "regVC",
            "vc_level":"200$",
            "portfolio_cash": 200000,
            "risk_adjustment": "0.1$0.3",
            "pos_limit": "poslimit",
            "standard_risk": "0.6",
            "volatility_threshold": 1.25
        },
        {
            "put_pct": 1, 
            "spread_adjustment": 0,
            "aa": 1,
            "risk_unit": .01,
            "model": "regVCSell",
            "vc_level":"200$",
            "portfolio_cash": 200000,
            "risk_adjustment": "0.1$0.3",
            "pos_limit": "poslimit",
            "standard_risk": "0.6",
            "volatility_threshold": 1.25
        },
        {
            "put_pct": 1, 
            "spread_adjustment": 0,
            "aa": 1,
            "risk_unit": .01,
            "model": "reg",
            "vc_level":"nvc",
            "portfolio_cash": 200000,
            "risk_adjustment": "0.1$0.3",
            "pos_limit": "poslimit",
            "standard_risk": "0.6",
            "volatility_threshold": 1.5
        },
        {
            "put_pct": 1, 
            "spread_adjustment": 0,
            "aa": 1,
            "risk_unit": .01,
            "model": "regVC",
            "vc_level":"200$",
            "portfolio_cash": 200000,
            "risk_adjustment": "0.1$0.3",
            "pos_limit": "poslimit",
            "standard_risk": "0.6",
            "volatility_threshold": 1.5
        },
        {
            "put_pct": 1, 
            "spread_adjustment": 0,
            "aa": 1,
            "risk_unit": .01,
            "model": "regVCSell",
            "vc_level":"200$",
            "portfolio_cash": 200000,
            "risk_adjustment": "0.1$0.3",
            "pos_limit": "poslimit",
            "standard_risk": "0.6",
            "volatility_threshold": 1.5
        },
        {
            "put_pct": 1, 
            "spread_adjustment": 0,
            "aa": 1,
            "risk_unit": .01,
            "model": "reg",
            "vc_level":"nvc",
            "portfolio_cash": 200000,
            "risk_adjustment": "0.1$0.3",
            "pos_limit": "noposlimit",
            "standard_risk": "0.6",
            "volatility_threshold": 1
        },
        {
            "put_pct": 1, 
            "spread_adjustment": 0,
            "aa": 1,
            "risk_unit": .01,
            "model": "regVC",
            "vc_level":"200$",
            "portfolio_cash": 200000,
            "risk_adjustment": "0.1$0.3",
            "pos_limit": "noposlimit",
            "standard_risk": "0.6",
            "volatility_threshold": 1
        },
        {
            "put_pct": 1, 
            "spread_adjustment": 0,
            "aa": 1,
            "risk_unit": .01,
            "model": "regVCSell",
            "vc_level":"200$",
            "portfolio_cash": 200000,
            "risk_adjustment": "0.1$0.3",
            "pos_limit": "noposlimit",
            "standard_risk": "0.6",
            "volatility_threshold": 1
        },
        {
            "put_pct": 1, 
            "spread_adjustment": 0,
            "aa": 1,
            "risk_unit": .01,
            "model": "reg",
            "vc_level":"nvc",
            "portfolio_cash": 200000,
            "risk_adjustment": "0.1$0.3",
            "pos_limit": "noposlimit",
            "standard_risk": "0.6",
            "volatility_threshold": 1.25
        },
        {
            "put_pct": 1, 
            "spread_adjustment": 0,
            "aa": 1,
            "risk_unit": .01,
            "model": "regVC",
            "vc_level":"200$",
            "portfolio_cash": 200000,
            "risk_adjustment": "0.1$0.3",
            "pos_limit": "noposlimit",
            "standard_risk": "0.6",
            "volatility_threshold": 1.25
        },
        {
            "put_pct": 1, 
            "spread_adjustment": 0,
            "aa": 1,
            "risk_unit": .01,
            "model": "regVCSell",
            "vc_level":"200$",
            "portfolio_cash": 200000,
            "risk_adjustment": "0.1$0.3",
            "pos_limit": "noposlimit",
            "standard_risk": "0.6",
            "volatility_threshold": 1.25
        },
        {
            "put_pct": 1, 
            "spread_adjustment": 0,
            "aa": 1,
            "risk_unit": .01,
            "model": "reg",
            "vc_level":"nvc",
            "portfolio_cash": 200000,
            "risk_adjustment": "0.1$0.3",
            "pos_limit": "noposlimit",
            "standard_risk": "0.6",
            "volatility_threshold": 1.5
        },
        {
            "put_pct": 1, 
            "spread_adjustment": 0,
            "aa": 1,
            "risk_unit": .01,
            "model": "regVC",
            "vc_level":"200$",
            "portfolio_cash": 200000,
            "risk_adjustment": "0.1$0.3",
            "pos_limit": "noposlimit",
            "standard_risk": "0.6",
            "volatility_threshold": 1.5
        },
        {
            "put_pct": 1, 
            "spread_adjustment": 0,
            "aa": 1,
            "risk_unit": .01,
            "model": "regVCSell",
            "vc_level":"200$",
            "portfolio_cash": 200000,
            "risk_adjustment": "0.1$0.3",
            "pos_limit": "noposlimit",
            "standard_risk": "0.6",
            "volatility_threshold": 1.5
        },
        {
            "put_pct": 1, 
            "spread_adjustment": 0,
            "aa": 1,
            "risk_unit": .01,
            "model": "reg",
            "vc_level":"nvc",
            "portfolio_cash": 200000,
            "risk_adjustment": "0.25$0.5",
            "pos_limit": "poslimit",
            "standard_risk": "0.8",
            "volatility_threshold": 1
        },
        {
            "put_pct": 1, 
            "spread_adjustment": 0,
            "aa": 1,
            "risk_unit": .01,
            "model": "regVC",
            "vc_level":"200$",
            "portfolio_cash": 200000,
            "risk_adjustment": "0.25$0.5",
            "pos_limit": "poslimit",
            "standard_risk": "0.8",
            "volatility_threshold": 1
        },
        {
            "put_pct": 1, 
            "spread_adjustment": 0,
            "aa": 1,
            "risk_unit": .01,
            "model": "regVCSell",
            "vc_level":"200$",
            "portfolio_cash": 200000,
            "risk_adjustment": "0.25$0.5",
            "pos_limit": "poslimit",
            "standard_risk": "0.8",
            "volatility_threshold": 1
        },
        {
            "put_pct": 1, 
            "spread_adjustment": 0,
            "aa": 1,
            "risk_unit": .01,
            "model": "reg",
            "vc_level":"nvc",
            "portfolio_cash": 200000,
            "risk_adjustment": "0.25$0.5",
            "pos_limit": "poslimit",
            "standard_risk": "0.8",
            "volatility_threshold": 1.25
        },
        {
            "put_pct": 1, 
            "spread_adjustment": 0,
            "aa": 1,
            "risk_unit": .01,
            "model": "regVC",
            "vc_level":"200$",
            "portfolio_cash": 200000,
            "risk_adjustment": "0.25$0.5",
            "pos_limit": "poslimit",
            "standard_risk": "0.8",
            "volatility_threshold": 1.25
        },
        {
            "put_pct": 1, 
            "spread_adjustment": 0,
            "aa": 1,
            "risk_unit": .01,
            "model": "regVCSell",
            "vc_level":"200$",
            "portfolio_cash": 200000,
            "risk_adjustment": "0.25$0.5",
            "pos_limit": "poslimit",
            "standard_risk": "0.8",
            "volatility_threshold": 1.25
        },
        {
            "put_pct": 1, 
            "spread_adjustment": 0,
            "aa": 1,
            "risk_unit": .01,
            "model": "reg",
            "vc_level":"nvc",
            "portfolio_cash": 200000,
            "risk_adjustment": "0.25$0.5",
            "pos_limit": "poslimit",
            "standard_risk": "0.8",
            "volatility_threshold": 1.5
        },
        {
            "put_pct": 1, 
            "spread_adjustment": 0,
            "aa": 1,
            "risk_unit": .01,
            "model": "regVC",
            "vc_level":"200$",
            "portfolio_cash": 200000,
            "risk_adjustment": "0.25$0.5",
            "pos_limit": "poslimit",
            "standard_risk": "0.8",
            "volatility_threshold": 1.5
        },
        {
            "put_pct": 1, 
            "spread_adjustment": 0,
            "aa": 1,
            "risk_unit": .01,
            "model": "regVCSell",
            "vc_level":"200$",
            "portfolio_cash": 200000,
            "risk_adjustment": "0.25$0.5",
            "pos_limit": "poslimit",
            "standard_risk": "0.8",
            "volatility_threshold": 1.5
        },
        {
            "put_pct": 1, 
            "spread_adjustment": 0,
            "aa": 1,
            "risk_unit": .01,
            "model": "reg",
            "vc_level":"nvc",
            "portfolio_cash": 200000,
            "risk_adjustment": "0.25$0.5",
            "pos_limit": "noposlimit",
            "standard_risk": "0.8",
            "volatility_threshold": 1
        },
        {
            "put_pct": 1, 
            "spread_adjustment": 0,
            "aa": 1,
            "risk_unit": .01,
            "model": "regVC",
            "vc_level":"200$",
            "portfolio_cash": 200000,
            "risk_adjustment": "0.25$0.5",
            "pos_limit": "noposlimit",
            "standard_risk": "0.8",
            "volatility_threshold": 1
        },
        {
            "put_pct": 1, 
            "spread_adjustment": 0,
            "aa": 1,
            "risk_unit": .01,
            "model": "regVCSell",
            "vc_level":"200$",
            "portfolio_cash": 200000,
            "risk_adjustment": "0.25$0.5",
            "pos_limit": "noposlimit",
            "standard_risk": "0.8",
            "volatility_threshold": 1
        },
        {
            "put_pct": 1, 
            "spread_adjustment": 0,
            "aa": 1,
            "risk_unit": .01,
            "model": "reg",
            "vc_level":"nvc",
            "portfolio_cash": 200000,
            "risk_adjustment": "0.25$0.5",
            "pos_limit": "noposlimit",
            "standard_risk": "0.8",
            "volatility_threshold": 1.25
        },
        {
            "put_pct": 1, 
            "spread_adjustment": 0,
            "aa": 1,
            "risk_unit": .01,
            "model": "regVC",
            "vc_level":"200$",
            "portfolio_cash": 200000,
            "risk_adjustment": "0.25$0.5",
            "pos_limit": "noposlimit",
            "standard_risk": "0.8",
            "volatility_threshold": 1.25
        },
        {
            "put_pct": 1, 
            "spread_adjustment": 0,
            "aa": 1,
            "risk_unit": .01,
            "model": "regVCSell",
            "vc_level":"200$",
            "portfolio_cash": 200000,
            "risk_adjustment": "0.25$0.5",
            "pos_limit": "noposlimit",
            "standard_risk": "0.8",
            "volatility_threshold": 1.25
        },
        {
            "put_pct": 1, 
            "spread_adjustment": 0,
            "aa": 1,
            "risk_unit": .01,
            "model": "reg",
            "vc_level":"nvc",
            "portfolio_cash": 200000,
            "risk_adjustment": "0.25$0.5",
            "pos_limit": "noposlimit",
            "standard_risk": "0.8",
            "volatility_threshold": 1.5
        },
        {
            "put_pct": 1, 
            "spread_adjustment": 0,
            "aa": 1,
            "risk_unit": .01,
            "model": "regVC",
            "vc_level":"200$",
            "portfolio_cash": 200000,
            "risk_adjustment": "0.25$0.5",
            "pos_limit": "noposlimit",
            "standard_risk": "0.8",
            "volatility_threshold": 1.5
        },
        {
            "put_pct": 1, 
            "spread_adjustment": 0,
            "aa": 1,
            "risk_unit": .01,
            "model": "regVCSell",
            "vc_level":"200$",
            "portfolio_cash": 200000,
            "risk_adjustment": "0.25$0.5",
            "pos_limit": "noposlimit",
            "standard_risk": "0.8",
            "volatility_threshold": 1.5
        }]

high_vol = [{
            "put_pct": 1, 
            "spread_adjustment": 0,
            "aa": 1,
            "risk_unit": .01,
            "model": "regAgg",
            "vc_level":"nvc",
            "portfolio_cash": 200000,
            "risk_adjustment": "0.25$0.5",
            "pos_limit": "noposlimit",
            "standard_risk": "0.8",
            "volatility_threshold": 1.5,
            "model_type": "reg",
            "floor_value": 0.9
        },
        {
            "put_pct": 1, 
            "spread_adjustment": 0,
            "aa": 1,
            "risk_unit": .01,
            "model": "regAggVC",
            "vc_level":"200$",
            "portfolio_cash": 200000,
            "risk_adjustment": "0.25$0.5",
            "pos_limit": "noposlimit",
            "standard_risk": "0.8",
            "volatility_threshold": 1.5,
            "model_type": "reg",
            "floor_value": 0.9
        },
        {
            "put_pct": 1, 
            "spread_adjustment": 0,
            "aa": 1,
            "risk_unit": .01,
            "model": "regAggVCSell",
            "vc_level":"200$",
            "portfolio_cash": 200000,
            "risk_adjustment": "0.25$0.5",
            "pos_limit": "noposlimit",
            "standard_risk": "0.8",
            "volatility_threshold": 1.5,
            "model_type": "reg",
            "floor_value": 0.9
        },
        {
            "put_pct": 1, 
            "spread_adjustment": 0,
            "aa": 1,
            "risk_unit": .01,
            "model": "regAgg",
            "vc_level":"nvc",
            "portfolio_cash": 200000,
            "risk_adjustment": "0.1$0.3",
            "pos_limit": "noposlimit",
            "standard_risk": "0.6",
            "volatility_threshold": 1.25,
            "model_type": "reg",
            "floor_value": 0.9
        },
        {
            "put_pct": 1, 
            "spread_adjustment": 0,
            "aa": 1,
            "risk_unit": .01,
            "model": "regAggVC",
            "vc_level":"200$",
            "portfolio_cash": 200000,
            "risk_adjustment": "0.1$0.3",
            "pos_limit": "noposlimit",
            "standard_risk": "0.6",
            "volatility_threshold": 1.25,
            "model_type": "reg",
            "floor_value": 0.9
        },
        {
            "put_pct": 1, 
            "spread_adjustment": 0,
            "aa": 1,
            "risk_unit": .01,
            "model": "regAggVCSell",
            "vc_level":"200$",
            "portfolio_cash": 200000,
            "risk_adjustment": "0.1$0.3",
            "pos_limit": "noposlimit",
            "standard_risk": "0.6",
            "volatility_threshold": 1.25,
            "model_type": "reg",
            "floor_value": 0.9
        },
        {
            "put_pct": 1, 
            "spread_adjustment": 0,
            "aa": 1,
            "risk_unit": .01,
            "model": "regAgg",
            "vc_level":"nvc",
            "portfolio_cash": 200000,
            "risk_adjustment": "0.25$0.5",
            "pos_limit": "noposlimit",
            "standard_risk": "0.8",
            "volatility_threshold": 1.25,
            "model_type": "reg",
            "floor_value": 0.9
        },
        {
            "put_pct": 1, 
            "spread_adjustment": 0,
            "aa": 1,
            "risk_unit": .01,
            "model": "regAggVC",
            "vc_level":"200$",
            "portfolio_cash": 200000,
            "risk_adjustment": "0.25$0.5",
            "pos_limit": "noposlimit",
            "standard_risk": "0.8",
            "volatility_threshold": 1.25,
            "model_type": "reg",
            "floor_value": 0.9
        },
        {
            "put_pct": 1, 
            "spread_adjustment": 0,
            "aa": 1,
            "risk_unit": .01,
            "model": "regAggVCSell",
            "vc_level":"200$",
            "portfolio_cash": 200000,
            "risk_adjustment": "0.25$0.5",
            "pos_limit": "noposlimit",
            "standard_risk": "0.8",
            "volatility_threshold": 1.25,
            "model_type": "reg",
            "floor_value": 0.9
        },
        {
            "put_pct": 1, 
            "spread_adjustment": 0,
            "aa": 1,
            "risk_unit": .01,
            "model": "regAgg",
            "vc_level":"nvc",
            "portfolio_cash": 200000,
            "risk_adjustment": "0.1$0.3",
            "pos_limit": "noposlimit",
            "standard_risk": "0.6",
            "volatility_threshold": 1.25,
            "model_type": "reg",
            "floor_value": 0.9
        },
        {
            "put_pct": 1, 
            "spread_adjustment": 0,
            "aa": 1,
            "risk_unit": .01,
            "model": "regAggVC",
            "vc_level":"200$",
            "portfolio_cash": 200000,
            "risk_adjustment": "0.1$0.3",
            "pos_limit": "noposlimit",
            "standard_risk": "0.6",
            "volatility_threshold": 1.25,
            "model_type": "reg",
            "floor_value": 0.9
        },
        {
            "put_pct": 1, 
            "spread_adjustment": 0,
            "aa": 1,
            "risk_unit": .01,
            "model": "regAggVCSell",
            "vc_level":"200$",
            "portfolio_cash": 200000,
            "risk_adjustment": "0.1$0.3",
            "pos_limit": "noposlimit",
            "standard_risk": "0.6",
            "volatility_threshold": 1.25,
            "model_type": "reg",
            "floor_value": 0.9
        }
]

classifer_configs=[
    {
            "put_pct": 1, 
            "spread_adjustment": 0,
            "aa": 1,
            "risk_unit": .01,
            "model": "cls",
            "vc_level":"nvc",
            "portfolio_cash": 200000,
            "risk_adjustment": "0.03",
            "pos_limit": "noposlimit",
            "standard_risk": "0.6",
            "volatility_threshold": 1.5,
            "model_type": "cls",
            "floor_value": 0.9
        },
        {
            "put_pct": 1, 
            "spread_adjustment": 0,
            "aa": 1,
            "risk_unit": .01,
            "model": "vc",
            "vc_level":"200$.03",
            "portfolio_cash": 200000,
            "risk_adjustment": "0.03",
            "pos_limit": "noposlimit",
            "standard_risk": "0.6",
            "volatility_threshold": 1.5,
            "model_type": "cls",
            "floor_value": 0.9
        },
        {
            "put_pct": 1, 
            "spread_adjustment": 0,
            "aa": 1,
            "risk_unit": .01,
            "model": "vcSell",
            "vc_level":"200$",
            "portfolio_cash": 200000,
            "risk_adjustment": "0.03",
            "pos_limit": "noposlimit",
            "standard_risk": "0.6",
            "volatility_threshold": 1.5,
            "model_type": "cls",
            "floor_value": 0.9
        },
        {
            "put_pct": 1, 
            "spread_adjustment": 0,
            "aa": 1,
            "risk_unit": .01,
            "model": "vc",
            "vc_level":"300$.03",
            "portfolio_cash": 200000,
            "risk_adjustment": "0.03",
            "pos_limit": "noposlimit",
            "standard_risk": "0.6",
            "volatility_threshold": 1.5,
            "model_type": "cls",
            "floor_value": 0.9
        },
        {
            "put_pct": 1, 
            "spread_adjustment": 0,
            "aa": 1,
            "risk_unit": .01,
            "model": "vcSell",
            "vc_level":"300$",
            "portfolio_cash": 200000,
            "risk_adjustment": "0.03",
            "pos_limit": "noposlimit",
            "standard_risk": "0.6",
            "volatility_threshold": 1.5,
            "model_type": "cls",
            "floor_value": 0.9
        },
        {
            "put_pct": 1, 
            "spread_adjustment": 0,
            "aa": 1,
            "risk_unit": .01,
            "model": "cls",
            "vc_level":"nvc",
            "portfolio_cash": 200000,
            "risk_adjustment": "0.05",
            "pos_limit": "noposlimit",
            "standard_risk": "0.6",
            "volatility_threshold": 1.5,
            "model_type": "cls",
            "floor_value": 0.9
        },
        {
            "put_pct": 1, 
            "spread_adjustment": 0,
            "aa": 1,
            "risk_unit": .01,
            "model": "vc",
            "vc_level":"200$.03",
            "portfolio_cash": 200000,
            "risk_adjustment": "0.05",
            "pos_limit": "noposlimit",
            "standard_risk": "0.6",
            "volatility_threshold": 1.5,
            "model_type": "cls",
            "floor_value": 0.9
        },
        {
            "put_pct": 1, 
            "spread_adjustment": 0,
            "aa": 1,
            "risk_unit": .01,
            "model": "vcSell",
            "vc_level":"200$",
            "portfolio_cash": 200000,
            "risk_adjustment": "0.05",
            "pos_limit": "noposlimit",
            "standard_risk": "0.6",
            "volatility_threshold": 1.5,
            "model_type": "cls",
            "floor_value": 0.9
        },
        {
            "put_pct": 1, 
            "spread_adjustment": 0,
            "aa": 1,
            "risk_unit": .01,
            "model": "vc",
            "vc_level":"300$.03",
            "portfolio_cash": 200000,
            "risk_adjustment": "0.05",
            "pos_limit": "noposlimit",
            "standard_risk": "0.6",
            "volatility_threshold": 1.5,
            "model_type": "cls",
            "floor_value": 0.9
        },
        {
            "put_pct": 1, 
            "spread_adjustment": 0,
            "aa": 1,
            "risk_unit": .01,
            "model": "vcSell",
            "vc_level":"300$",
            "portfolio_cash": 200000,
            "risk_adjustment": "0.05",
            "pos_limit": "noposlimit",
            "standard_risk": "0.6",
            "volatility_threshold": 1.5,
            "model_type": "cls",
            "floor_value": 0.9
        },
]